-- Initialize schemas for AutoAgent-Dashboard

-- 1. Table: products
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    stock_quantity INT NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    price NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (price >= 0.00),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Table: sales_records
CREATE TABLE IF NOT EXISTS sales_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (amount >= 0.00),
    sale_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index on product_id to optimize foreign key constraints and joins
CREATE INDEX IF NOT EXISTS idx_sales_records_product_id ON sales_records(product_id);

-- 3. Table: agent_workflows
CREATE TABLE IF NOT EXISTS agent_workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_query TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    tokens_used INT DEFAULT 0,
    latency_ms INT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Table: workflow_steps
CREATE TABLE IF NOT EXISTS workflow_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL REFERENCES agent_workflows(id) ON DELETE CASCADE,
    step_name TEXT NOT NULL,
    sql_generated TEXT,
    execution_result TEXT,
    is_success BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index on workflow_id for JOIN speed and CASCADE performance
CREATE INDEX IF NOT EXISTS idx_workflow_steps_workflow_id ON workflow_steps(workflow_id);
